import PDFDocument from 'pdfkit';

export function generatePayslipPDF(record: any, employee: any, org: any): Promise<Buffer> {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ size: 'A4', margin: 40 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    const month = record.payrollRun?.month || 1;
    const year = record.payrollRun?.year || 2026;
    const monthName = new Date(year, month - 1).toLocaleString('en', { month: 'long' });

    // Header
    doc.fontSize(18).font('Helvetica-Bold').text(org?.name || 'Go2-Payroll', 40, 40);
    doc.fontSize(9).font('Helvetica').fillColor('#666').text(org?.address || '', 40, 62);
    doc.fillColor('#000').fontSize(12).font('Helvetica-Bold').text(`PAYSLIP — ${monthName} ${year}`, 40, 90);
    doc.moveTo(40, 110).lineTo(555, 110).strokeColor('#E7E2D8').stroke();

    // Employee Info
    const y1 = 125;
    doc.fontSize(9).font('Helvetica');
    doc.text(`Employee: ${employee?.firstName || ''} ${employee?.lastName || ''}`, 40, y1);
    doc.text(`Code: ${employee?.employeeCode || ''}`, 40, y1 + 14);
    doc.text(`Department: ${employee?.department?.name || '-'}`, 300, y1);
    doc.text(`Designation: ${employee?.designation?.name || '-'}`, 300, y1 + 14);
    doc.text(`PAN: ${employee?.panNumber || '-'}`, 40, y1 + 28);
    doc.text(`UAN: ${employee?.uanNumber || '-'}`, 300, y1 + 28);
    doc.text(`Bank A/C: ${employee?.bankAccountNo || '-'}`, 40, y1 + 42);
    doc.text(`IFSC: ${employee?.bankIfsc || '-'}`, 300, y1 + 42);

    doc.moveTo(40, y1 + 60).lineTo(555, y1 + 60).stroke();

    // Attendance
    const y2 = y1 + 75;
    doc.font('Helvetica-Bold').text('Attendance', 40, y2);
    doc.font('Helvetica');
    doc.text(`Working Days: ${record.workingDays}`, 40, y2 + 16);
    doc.text(`Paid Days: ${record.paidDays}`, 180, y2 + 16);
    doc.text(`LOP Days: ${record.lopDays}`, 320, y2 + 16);

    // Earnings & Deductions
    const y3 = y2 + 45;
    doc.font('Helvetica-Bold').fontSize(10).text('EARNINGS', 40, y3);
    doc.text('DEDUCTIONS', 320, y3);
    doc.moveTo(40, y3 + 14).lineTo(280, y3 + 14).stroke();
    doc.moveTo(320, y3 + 14).lineTo(555, y3 + 14).stroke();

    doc.fontSize(9).font('Helvetica');
    const earnings = record.earnings || {};
    const deductions = record.deductions || {};
    let ey = y3 + 22;

    Object.entries(earnings).forEach(([key, val]: [string, any]) => {
      doc.text(key.replace(/_/g, ' ').toUpperCase(), 40, ey);
      doc.text(`₹${Number(val).toLocaleString('en-IN')}`, 220, ey, { align: 'right', width: 60 });
      ey += 16;
    });

    let dy = y3 + 22;
    Object.entries(deductions).forEach(([key, val]: [string, any]) => {
      doc.text(key.replace(/_/g, ' ').toUpperCase(), 320, dy);
      doc.text(`₹${Number(val).toLocaleString('en-IN')}`, 495, dy, { align: 'right', width: 60 });
      dy += 16;
    });

    // Totals
    const yTotal = Math.max(ey, dy) + 10;
    doc.moveTo(40, yTotal).lineTo(555, yTotal).stroke();
    doc.font('Helvetica-Bold').fontSize(10);
    doc.text(`Gross: ₹${record.grossEarnings?.toLocaleString('en-IN')}`, 40, yTotal + 8);
    doc.text(`Deductions: ₹${record.totalDeductions?.toLocaleString('en-IN')}`, 320, yTotal + 8);

    // Net Pay
    const yNet = yTotal + 30;
    doc.rect(40, yNet, 515, 30).fillAndStroke('#F5F1E6', '#E7E2D8');
    doc.fillColor('#2B2B2B').fontSize(12).font('Helvetica-Bold');
    doc.text(`NET PAY: ₹${record.netPay?.toLocaleString('en-IN')}`, 50, yNet + 8);

    // Footer
    doc.fontSize(8).font('Helvetica').fillColor('#999');
    doc.text('This is a system-generated payslip and does not require a signature.', 40, 750, { align: 'center', width: 515 });
    doc.text(`Generated by Go2-Payroll on ${new Date().toLocaleDateString()}`, 40, 762, { align: 'center', width: 515 });

    doc.end();
  });
}
